In [1]:
distance = [10,15,17,26,20]
time = [0.3,0.47,0.55,1.2,1.0]

In [2]:
speed = []
for i in range(len(distance)):
    speed.append(distance[i]/time[i])

speed

[33.333333333333336,
 31.914893617021278,
 30.909090909090907,
 21.666666666666668,
 20.0]

In [3]:
prod_quantity = [13,5,6,10,11]
price = [1.2,3.2,1,4.5,6]

In [7]:
!pip install numpy

In [8]:
!pip install --upgrade pip

In [9]:
import numpy as np
print(np.__version__)

1.19.4


In [10]:
arr = np.array([1,2,3,4,5])
print(type(arr))

<class 'numpy.ndarray'>


In [15]:
dis = np.array(distance)
time = np.array(time)

print(dis/time)

[33.33333333 31.91489362 30.90909091 21.66666667 20.        ]


In [24]:
arr = np.array([[1,2,3],[4,5,6]])

print(arr)
print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [25]:
arr = np.zeros((4,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [1]:
import numpy as np
arr = np.random.randn(3,4)
arr

array([[-1.0958092 ,  1.05595438, -0.20856033, -0.85463786],
       [-1.30734182, -2.11740379,  0.96956037,  0.14561262],
       [ 0.97907564,  0.15163795, -0.38035623, -0.14479809]])

In [2]:
#INDEXING AND SLICING
arr[1]

array([-1.30734182, -2.11740379,  0.96956037,  0.14561262])

In [7]:
arr = np.arange(12).reshape(2,2,3) #2 arrays 2 rows 3 col
arr

#arange() measn elements from 0 to n-1
#reshape() shapes elements in given dimensions

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [8]:
arr[0]

array([[0, 1, 2],
       [3, 4, 5]])

In [9]:
arr[-1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
arr = np.arange(10)
arr
print(arr[5:8]) # will slice elements from 5
print(arr[:-5])

[5 6 7]
[0 1 2 3 4]


In [17]:
arr = np.arange(18).reshape(3,2,3) #2 arrays 2 rows 3 col
arr

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [18]:
arr[1:2]

array([[[ 6,  7,  8],
        [ 9, 10, 11]]])

In [19]:
arr[0:3:2]

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[12, 13, 14],
        [15, 16, 17]]])

In [20]:
arr[1]

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [22]:
arr[1:2:3]

array([[[ 6,  7,  8],
        [ 9, 10, 11]]])

In [26]:
arr[1,:,1]

array([ 7, 10])

In [27]:
arr[...,2]

array([[ 2,  5],
       [ 8, 11],
       [14, 17]])

In [28]:
cities = np.array(["Delhi","Banglore","Mumbai","Chennai","surat"])
city_data = np.random.randn(5,3)
city_data

array([[ 0.8304009 ,  0.20143565,  1.1579297 ],
       [-0.45508085,  1.40694037, -0.88621418],
       [-1.05937966,  1.26051565,  1.23392441],
       [ 1.58649483, -0.41464661, -0.36530511],
       [-0.43304643,  0.20316144, -0.40956719]])

In [30]:
city_data[cities == "Mumbai"]

array([[-1.05937966,  1.26051565,  1.23392441]])

In [31]:
print(cities == "Mumbai")

[False False  True False False]


In [32]:
city_data[cities == "bombay"]

array([], shape=(0, 3), dtype=float64)

In [33]:
city_data[city_data > 0]

array([0.8304009 , 0.20143565, 1.1579297 , 1.40694037, 1.26051565,
       1.23392441, 1.58649483, 0.20316144])

In [34]:
city_data[city_data < 0] = 0
city_data

array([[0.8304009 , 0.20143565, 1.1579297 ],
       [0.        , 1.40694037, 0.        ],
       [0.        , 1.26051565, 1.23392441],
       [1.58649483, 0.        , 0.        ],
       [0.        , 0.20316144, 0.        ]])

In [35]:
arr = np.arange(15).reshape(3,5) 
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
arr + 5

array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [37]:
arr * 2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [38]:
arr1 = np.arange(15).reshape(5,3)
arr2 = np.arange(5).reshape(5,1)
arr2 + arr1

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14],
       [16, 17, 18]])

In [45]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[10,11,12],[13,14,15],[16,17,18]])

In [46]:
A.dot(B)

array([[ 84,  90,  96],
       [201, 216, 231],
       [318, 342, 366]])

In [47]:
A.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])